# Base16 Mocha 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  # Default colors
  primary:
    background: '0x3b3228'
    foreground: '0xd0c8c6'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x3b3228'
    cursor: '0xd0c8c6'

  # Normal colors
  normal:
    black:   '0x3b3228'
    red:     '0xcb6077'
    green:   '0xbeb55b'
    yellow:  '0xf4bc87'
    blue:    '0x8ab3b5'
    magenta: '0xa89bb9'
    cyan:    '0x7bbda4'
    white:   '0xd0c8c6'

  # Bright colors
  bright:
    black:   '0x7e705a'
    red:     '0xcb6077'
    green:   '0xbeb55b'
    yellow:  '0xf4bc87'
    blue:    '0x8ab3b5'
    magenta: '0xa89bb9'
    cyan:    '0x7bbda4'
    white:   '0xf5eeeb'

  indexed_colors:
    - { index: 16, color: '0xd28b71' }
    - { index: 17, color: '0xbb9584' }
    - { index: 18, color: '0x534636' }
    - { index: 19, color: '0x645240' }
    - { index: 20, color: '0xb8afad' }
    - { index: 21, color: '0xe9e1dd' }
