# Base16 Solarized Light 256 - alacritty color config
# Ethan Schoonover (modified by aramisgithub)
colors:
  # Default colors
  primary:
    background: '0xfdf6e3'
    foreground: '0x586e75'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfdf6e3'
    cursor: '0x586e75'

  # Normal colors
  normal:
    black:   '0xfdf6e3'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0x6c71c4'
    cyan:    '0x2aa198'
    white:   '0x586e75'

  # Bright colors
  bright:
    black:   '0x839496'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0x6c71c4'
    cyan:    '0x2aa198'
    white:   '0x002b36'

  indexed_colors:
    - { index: 16, color: '0xcb4b16' }
    - { index: 17, color: '0xd33682' }
    - { index: 18, color: '0xeee8d5' }
    - { index: 19, color: '0x93a1a1' }
    - { index: 20, color: '0x657b83' }
    - { index: 21, color: '0x073642' }
