[colors.primary]
background = "#fdf6e3"
foreground = "#5c6a72"

# [colors.cursor]
# text = "0x3b3228"
# cursor = "0xd0c8c6"

[colors.normal]
black = "#5c6a72"
red = "#f85552"
green = "#8da101"
yellow = "#dfa000"
blue = "#3a94c5"
magenta = "#df69ba"
cyan = "#35a77c"
white = "#e0dcc7"

[colors.bright]
black = "#5c6a72"
red = "#f85552"
green = "#8da101"
yellow = "#dfa000"
blue = "#3a94c5"
magenta = "#df69ba"
cyan = "#35a77c"
white = "#e0dcc7"

# [colors]
# indexed_colors = [
#   { index = 16, color = "0xd28b71" },
#   { index = 17, color = "0xbb9584" },
#   { index = 18, color = "0x534636" },
#   { index = 19, color = "0x645240" },
#   { index = 20, color = "0xb8afad" },
#   { index = 21, color = "0xe9e1dd" },
# ]
