#!/bin/sh
#
# Builds a custom xmonad exectable as defined by xmonad.hs, and named as the
# first argument to this script.

stack build --only-dependencies
exec stack ghc -- \
  --make xmonad.hs \
  -i \
  -ilib \
  -fforce-recomp \
  -main-is main \
  -O2 \
  -j"$(nproc)" \
  -o "$1"
