#!/bin/bash
#
# Defines color scheme variables
# Use in other scripts as 'source ~/.colors'


# Base16 theme
export B_BASE00='#002B36'  # Background, "black"
export B_BASE01='#073642'  # Highlighted background
export B_BASE02='#586E75'  # Inversion foreground
export B_BASE03='#657B83'  # "bright black"
export B_BASE04='#839496'  # Secondary foreground, inversion background
export B_BASE05='#93A1A1'  # Normal foreground, "white"
export B_BASE06='#EEE8D5'
export B_BASE07='#FDF6E3'  # Slight emphasis, "bright white"
export B_BASE08='#DC322F'  # Red, error, urgent warning
export B_BASE09='#CB4B16'  # Orange/rust
export B_BASE0A='#B58900'  # Yellow, emphasis, warning
export B_BASE0B='#859900'  # Green, ok/success
export B_BASE0C='#2AA198'  # Cyan
export B_BASE0D='#268BD2'  # Blue, accent colour
export B_BASE0E='#6C71C4'  # Purple/magenta
export B_BASE0F='#D33682'  # Light brown

export PRIMARY_CONTENT_COLOR=$B_BASE02
export BACKGROUND_COLOR=$B_BASE07
export SECONDARY_CONTENT_COLOR=$B_BASE03
export SLIGHTLY_EMPHASIZED_CONTENT_COLOR=$B_BASE00
export EMPHASIZED_CONTENT_COLOR=$B_BASE0A
export INVERSE_CONTENT_COLOR=$B_BASE06
export INVERSE_BACKGROUND_COLOR=$B_BASE03
export BACKGROUND_HIGHLIGHT_COLOR=$B_BASE06
export ACCENT_COLOR=$B_BASE0D

export OK_COLOR=$B_BASE0B
export WARNING_COLOR=$B_BASE0A
export URGENT_WARNING_COLOR=$B_BASE08
export ERROR_COLOR=$URGENT_WARNING_COLOR
