#!/bin/bash
#
# HLWM settings

script_dir=$(dirname $BASH_SOURCE)

hc() { herbstclient "$@" ; }

hc emit_hook reload


### KEY AND MOUSE BINDINGS ###

source "$script_dir/bindings.sh"

# Tags
tag_names=( mail web terms 4 5 6 7 )
tag_keys=( ampersand eacute quotedbl apostrophe parenleft section egrave )
hc rename default "${tag_names[0]}" 2>/dev/null || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


### THEME ###

source "$script_dir/theme.sh"


### RULES ###

source "$script_dir/rules.sh"


# Unlock, just to be sure
hc unlock


### MULTI MONITOR SETUP ###

find_orientation() {
    zenity \
        --title 'Orientation' \
        --text 'Where is the external monitor?' \
        --list \
        --column orientation \
        left right
}

# Removes disconnected monitors
xrandr --auto
xrandr --output LVDS1 --auto
if grep -q "VGA1 connected" <(xrandr); then
    orientation=$(find_orientation)
    xrandr --output VGA1 --auto --${orientation:-right}-of LVDS1
elif  grep -q "HDMI1 connected" <(xrandr); then
    orientation=$(find_orientation)
    xrandr --output HDMI1 --auto --${orientation:-right}-of LVDS1
fi

hc detect_monitors
# Or manual:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0


### PANEL ###
panel="$script_dir/dzen/panel.sh"
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# Start panel on each monitor
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    "$panel" $monitor &
done
