#!/bin/bash
#
# HLWM settings

script_dir=$(dirname $BASH_SOURCE)

hc() { herbstclient "$@" ; }

hc emit_hook reload


### KEY AND MOUSE BINDINGS ###

source "$script_dir/bindings.sh"

# Tags
tag_names=( mail web terms 4 5 6 7 )
tag_keys=( ampersand eacute quotedbl apostrophe parenleft section egrave )
hc rename default "${tag_names[0]}" 2>/dev/null || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


### THEME ###

source "$script_dir/theme.sh"


### RULES ###

source "$script_dir/rules.sh"


# Unlock, just to be sure
hc unlock


### MULTI MONITOR SETUP ###
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors


### PANEL ###
panel="$script_dir/panel.sh"
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# Start panel on each monitor
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    "$panel" $monitor &
done


### BACKGROUND ###
$HOME/.fehbg


### LAUNCH SOME PROGRAMS ###
thunderbird &
firefox &
